<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DashboardTotal Kasus Perkembangan COVID_589791</name>
   <tag></tag>
   <elementGuidId>47f21664-0744-4286-9bc1-0811ac42d98f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-span-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d4f0dc5c-8d4c-4cec-988f-4cc5ab684e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-span-3</value>
      <webElementGuid>d0babc59-c11e-4449-9711-1771361737c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DashboardTotal Kasus Perkembangan COVID-19 Hari ini di IndonesiaPositif COVID6090509Sembuh5916854Meninggal156740Tentang Penyakit Coronavirus (COVID-19)Informasi mengenai gejala yang timbul, cara penyembuhan, dan pencegahan dari penyakit coronavirusGejalaPerawatanPencegahanMasing-masing orang memiliki respons yang berbeda terhadap COVID-19. Sebagian besar orang yang terpapar virus ini akan mengalami gejala ringan hingga sedang, dan akan pulih tanpa perlu dirawat di rumah sakit.Gejala yang paling umum :DemamBatukKelelahanKehilangan Rasa atau BauGejala yang sedikit tidak umum :Sakit TenggorokanSakit KepalaSakit dan NyeriDiareRuam pada Kulit, atau perubahan warna pada jari tangan atau jari kakiMata Merah atau IritasiGejala Serius :Kesulitan bernapas atau sesak napasKesulitan berbicara atau bergerak, atau bingungNyeri DadaSegera cari bantuan medis jika Anda mengalami gejala serius. Selalu hubungi dokter atau fasilitas kesehatan sebelum mengunjunginya. Orang dengan gejala ringan yang dinyatakan sehat harus melakukan perawatan mandiri di rumah. Rata-rata gejala akan muncul 5–6 hari setelah seseorang pertama kali terinfeksi virus ini, tetapi bisa juga sampai 14 hari setelah terinfeksi.</value>
      <webElementGuid>bad49933-b3e3-4d97-8817-b06b4ed48905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-container&quot;]/main[1]/div[@class=&quot;home&quot;]/div[@class=&quot;ml-5 mt-5&quot;]/div[@class=&quot;grid lg:grid-cols-4 gap-x-2.5 grid-cols-1&quot;]/div[@class=&quot;col-span-3&quot;]</value>
      <webElementGuid>8738e938-adcf-4176-bb25-d351d011ebab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div/div</value>
      <webElementGuid>6ee3d283-7a23-4489-8ad4-29eb6ce19e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[2]</value>
      <webElementGuid>57e91d80-8dd4-4d1e-b2dc-63e3ffb171c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[4]</value>
      <webElementGuid>ce33bf18-0603-412b-bbc2-c327d4d36be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div</value>
      <webElementGuid>d3c08c49-0676-48d2-bd1a-636dd4caace4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DashboardTotal Kasus Perkembangan COVID-19 Hari ini di IndonesiaPositif COVID6090509Sembuh5916854Meninggal156740Tentang Penyakit Coronavirus (COVID-19)Informasi mengenai gejala yang timbul, cara penyembuhan, dan pencegahan dari penyakit coronavirusGejalaPerawatanPencegahanMasing-masing orang memiliki respons yang berbeda terhadap COVID-19. Sebagian besar orang yang terpapar virus ini akan mengalami gejala ringan hingga sedang, dan akan pulih tanpa perlu dirawat di rumah sakit.Gejala yang paling umum :DemamBatukKelelahanKehilangan Rasa atau BauGejala yang sedikit tidak umum :Sakit TenggorokanSakit KepalaSakit dan NyeriDiareRuam pada Kulit, atau perubahan warna pada jari tangan atau jari kakiMata Merah atau IritasiGejala Serius :Kesulitan bernapas atau sesak napasKesulitan berbicara atau bergerak, atau bingungNyeri DadaSegera cari bantuan medis jika Anda mengalami gejala serius. Selalu hubungi dokter atau fasilitas kesehatan sebelum mengunjunginya. Orang dengan gejala ringan yang dinyatakan sehat harus melakukan perawatan mandiri di rumah. Rata-rata gejala akan muncul 5–6 hari setelah seseorang pertama kali terinfeksi virus ini, tetapi bisa juga sampai 14 hari setelah terinfeksi.' or . = 'DashboardTotal Kasus Perkembangan COVID-19 Hari ini di IndonesiaPositif COVID6090509Sembuh5916854Meninggal156740Tentang Penyakit Coronavirus (COVID-19)Informasi mengenai gejala yang timbul, cara penyembuhan, dan pencegahan dari penyakit coronavirusGejalaPerawatanPencegahanMasing-masing orang memiliki respons yang berbeda terhadap COVID-19. Sebagian besar orang yang terpapar virus ini akan mengalami gejala ringan hingga sedang, dan akan pulih tanpa perlu dirawat di rumah sakit.Gejala yang paling umum :DemamBatukKelelahanKehilangan Rasa atau BauGejala yang sedikit tidak umum :Sakit TenggorokanSakit KepalaSakit dan NyeriDiareRuam pada Kulit, atau perubahan warna pada jari tangan atau jari kakiMata Merah atau IritasiGejala Serius :Kesulitan bernapas atau sesak napasKesulitan berbicara atau bergerak, atau bingungNyeri DadaSegera cari bantuan medis jika Anda mengalami gejala serius. Selalu hubungi dokter atau fasilitas kesehatan sebelum mengunjunginya. Orang dengan gejala ringan yang dinyatakan sehat harus melakukan perawatan mandiri di rumah. Rata-rata gejala akan muncul 5–6 hari setelah seseorang pertama kali terinfeksi virus ini, tetapi bisa juga sampai 14 hari setelah terinfeksi.')]</value>
      <webElementGuid>3354017d-d782-4a32-9122-e8d00cae6087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
